### ISSUE TITLE
Null Pointer Exception found in log files

### ISSUE THREAD

**Issue by sferrin** [hivemq/hivemq-community-edition#170]
## Expected behavior
NullPointerException does not happen.

## Actual behavior
On a daily basis the java.lang.NullPointerException is found in the hivemq.{date}.log files around 134718 to 134858 times per day. 

## To Reproduce
We are an IoT industry that has 1500-2000 that are currently able to connect to the hive. We find these error messages in the log on a daily basis. The exact error message reads: "ERROR - An unexpected error occurred for client with IP <insert IP>"

### Stack Trace
ERROR - An unexpected error occurred for client with IP <insert IP>: java.lang.NullPointerException
        at com.hivemq.persistence.payload.PublishPayloadPersistenceImpl.add(PublishPayloadPersistenceImpl.java:128)
        at com.hivemq.persistence.clientsession.ClientSessionPersistenceImpl.clientConnected(ClientSessionPersistenceImpl.java:164)
        at com.hivemq.mqtt.handler.connect.ConnectPersistenceUpdateHandler.updatePersistenceData(ConnectPersistenceUpdateHandler.java:87)
        at com.hivemq.mqtt.handler.connect.ConnectPersistenceUpdateHandler.userEventTriggered(ConnectPersistenceUpdateHandler.java:78)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
        at io.netty.channel.ChannelInboundHandlerAdapter.userEventTriggered(ChannelInboundHandlerAdapter.java:108)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:329)
        at io.netty.channel.AbstractChannelHandlerContext.invokeUserEventTriggered(AbstractChannelHandlerContext.java:315)
        at io.netty.channel.AbstractChannelHandlerContext.fireUserEventTriggered(AbstractChannelHandlerContext.java:307)
        at com.hivemq.mqtt.handler.connect.ConnectHandler.afterTakeover(ConnectHandler.java:564)
        at com.hivemq.mqtt.handler.connect.ConnectHandler.access$000(ConnectHandler.java:88)
        at com.hivemq.mqtt.handler.connect.ConnectHandler$1.onSuccess(ConnectHandler.java:468)
        at com.hivemq.mqtt.handler.connect.ConnectHandler$1.onSuccess(ConnectHandler.java:465)
        at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1062)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:474)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:909)
        at java.base/java.lang.Thread.run(Thread.java:834)

## Details
- Affected HiveMQ CE version(s): 2019.1
- Used JVM version:
openjdk version "11.0.7" 2020-04-14
OpenJDK Runtime Environment (build 11.0.7+10-post-Ubuntu-2ubuntu218.04)
OpenJDK 64-Bit Server VM (build 11.0.7+10-post-Ubuntu-2ubuntu218.04, mixed mode, sharing)

**Comment by SgtSilvio** [comment]
Hi @sferrin 
Please provide more details by filling out the issue template.

**Comment by sferrin** [comment]
@SgtSilvio template has been completed.

**Comment by SgtSilvio** [comment]
Please also provide the stack traces from the logs?

**Comment by sferrin** [comment]
@SgtSilvio Stack trace provided under steps to reproduce.

**Comment by SgtSilvio** [comment]
@sferrin Thank you for the information. Another question: you mentioned that this exception occurs 100000+ times a day. Is it always the exact same stack trace?

**Comment by sferrin** [comment]
From what I've seen the last few days, it is always the same stack trace.

Thanks,

*Spencer Ferrin*
Software Engineer Team Lead
sferrin@freeus.com
Cell: 801-814-1720

**Comment by sferrin** [comment]
@SgtSilvio do you have a status on this?

**Comment by SgtSilvio** [comment]
@sferrin Sorry for the delayed response.
The current status is that your information was passed to our development team.

**Comment by DC2-DanielKrueger** [comment]
Is the bug still occurring with the recent release? @sferrin
