### ISSUE TITLE
Remove awt dependency for stripped JVM configurations

### ISSUE THREAD

**Issue by flxo** [hivemq/hivemq-community-edition#175]
## Problem or use case

We're intending to run `HiveMQ` in a headless embedded environment. The desired JVM configuration does not contains `awt`. Somewhere down the track from the configuration file parsing (via xml) there's a dependency to `awt`. 

Here's the corresponding exception:

```
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    Uncaught exception in thread embedded-hivemq-state-change-executor
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    java.lang.NoClassDefFoundError: java/awt/Component
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl.<clinit>(RuntimeBuiltinLeafInfoImpl.java:355)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.model.impl.RuntimeTypeInfoSetImpl.<init>(RuntimeTypeInfoSetImpl.java:33)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:98)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.createTypeInfoSet(RuntimeModelBuilder.java:54)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.model.impl.ModelBuilder.<init>(ModelBuilder.java:132)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.model.impl.RuntimeModelBuilder.<init>(RuntimeModelBuilder.java:62)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.runtime.JAXBContextImpl.getTypeInfoSet(JAXBContextImpl.java:425)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:273)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.runtime.JAXBContextImpl.<init>(JAXBContextImpl.java:109)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.runtime.JAXBContextImpl$JAXBContextBuilder.build(JAXBContextImpl.java:1126)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.sun.xml.bind.v2.ContextFactory.createContext(ContextFactory.java:135)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/java.lang.reflect.Method.invoke(Method.java:566)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:262)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:249)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at javax.xml.bind.ContextFinder.find(ContextFinder.java:456)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:656)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:599)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.hivemq.configuration.reader.ConfigFileReader.setConfigFromXML(ConfigFileReader.java:104)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.hivemq.configuration.reader.ConfigFileReader.applyConfig(ConfigFileReader.java:75)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.hivemq.configuration.ConfigurationBootstrap.bootstrapConfig(ConfigurationBootstrap.java:57)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at com.hivemq.embedded.internal.EmbeddedHiveMQImpl.stateChange(EmbeddedHiveMQImpl.java:138)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/java.lang.Thread.run(Thread.java:834)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    Caused by: java.lang.ClassNotFoundException: java.awt.Component
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
01:26:37.008 com.hivemq.util.Unca (3057   36)  E    ... 27 more
```

## Preferred solution or suggestions

Is it possible to somehow omit this dependency? For sure we can add features but `awt` sounds spooky for obvious reasons.

**Comment by schaebo** [comment]
Hi flxo,

unfortunately the dependency on awt comes from the used JAXB implementation which for some reason imports awt classes directly. We cannot exclude the JAXB implementation as this is used e.g. for reading the configuration file.

We will investigate if there is a solution for this.

**Comment by flxo** [comment]
Thanks. Feel free to close this issue if the effort is too high (probably it is). I'll patch our jvm config accordingly.

**Comment by MicWalter** [comment]
This should have been closed long ago. 
Reason for wonfix: The effort to remove the AWT dependency is to big (in relation to the problem), especially if there is a workaround.
