### ISSUE TITLE
DataCorruptionException: DataIterator: no more bytes available, address = 10547, file = 00000000000.xd (?)

### ISSUE THREAD

**Issue by jayjupdhig** [hivemq/hivemq-community-edition#208]
## Expected behavior
No exception

## Actual behavior
DataCorruptionException: DataIterator: no more bytes available, address = 10547, file = 00000000000.xd

## To Reproduce
Does not seem to be reprouceable for me

### Reproducer code
Don't know...

## Details
- Affected HiveMQ CE version(s): 
2020.3

- Used JVM version:
Zulu JVM Java 11 LTS

- OS Debian 9 with most current updates on 2020-09-03

Exception message on HiveMQ CE start is here:

```
2020-09-03 12:42:13,708 INFO  - Starting HiveMQ Community Edition Server
2020-09-03 12:42:13,711 INFO  - HiveMQ version: 2020.3
2020-09-03 12:42:13,711 INFO  - HiveMQ home directory: /opt/hivemq-ce-2020.3
2020-09-03 12:42:13,815 INFO  - Log Configuration was overridden by /opt/hivemq-ce-2020.3/conf/logback.xml
2020-09-03 12:42:14,186 INFO  - This HiveMQ ID is njs4d
2020-09-03 12:42:17,610 ERROR - Exception on Log recovery. Approved high address = 10511
jetbrains.exodus.log.DataCorruptionException: DataIterator: no more bytes available, address = 10547, file = 00000000000.xd
	at jetbrains.exodus.log.DataCorruptionException.raise(DataCorruptionException.java:33)
	at jetbrains.exodus.log.DataIterator.next(DataIterator.java:62)
	at jetbrains.exodus.log.CompressedUnsignedLongByteIterable.getInt(CompressedUnsignedLongByteIterable.java:112)
	at jetbrains.exodus.log.Log.read(Log.java:523)
	at jetbrains.exodus.log.Log.read(Log.java:508)
	at jetbrains.exodus.log.Log.read(Log.java:495)
	at jetbrains.exodus.log.LoggableIterator.next(LoggableIterator.java:46)
	at jetbrains.exodus.log.LoggableIterator.next(LoggableIterator.java:25)
	at jetbrains.exodus.log.Log.<init>(Log.java:144)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
	at com.hivemq.persistence.local.xodus.XodusLocalPersistence.lambda$start$2(XodusLocalPersistence.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-03 12:42:17,704 ERROR - Exception on Log recovery. Approved high address = 9904
jetbrains.exodus.log.DataCorruptionException: DataIterator: no more bytes available, address = 10010, file = 00000000000.xd
	at jetbrains.exodus.log.DataCorruptionException.raise(DataCorruptionException.java:33)
	at jetbrains.exodus.log.DataIterator.next(DataIterator.java:62)
	at jetbrains.exodus.log.CompressedUnsignedLongByteIterable.getInt(CompressedUnsignedLongByteIterable.java:112)
	at jetbrains.exodus.log.Log.read(Log.java:523)
	at jetbrains.exodus.log.Log.read(Log.java:508)
	at jetbrains.exodus.log.Log.read(Log.java:495)
	at jetbrains.exodus.log.LoggableIterator.next(LoggableIterator.java:46)
	at jetbrains.exodus.log.LoggableIterator.next(LoggableIterator.java:25)
	at jetbrains.exodus.log.Log.<init>(Log.java:144)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
	at com.hivemq.persistence.local.xodus.XodusLocalPersistence.lambda$start$2(XodusLocalPersistence.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-09-03 12:42:18,504 INFO  - Starting with file persistences
2020-09-03 12:42:19,327 INFO  - Starting HiveMQ extension system.
2020-09-03 12:42:19,442 WARN  - 
################################################################################################################
# This HiveMQ deployment is not secure! You are lacking Authentication and Authorization.                      #
# Right now any MQTT client can connect to the broker with a full set of permissions.                          #
# For production usage, add an appropriate security extension and remove the hivemq-allow-all extension.       #
# You can download security extensions from the HiveMQ Marketplace (https://www.hivemq.com/extensions/).       #
################################################################################################################
2020-09-03 12:42:19,461 INFO  - Starting TCP listener on address 0.0.0.0 and port 1883
2020-09-03 12:42:19,465 INFO  - Extension "Allow All Extension" version 1.0.0 started successfully.
2020-09-03 12:42:19,513 INFO  - Started TCP Listener on address 0.0.0.0 and on port 1883
2020-09-03 12:42:19,514 INFO  - Started HiveMQ in 5821ms
2020-09-03 12:42:28,110 WARN  - Tried to decrement a payload reference counter (187208) that was already zero.
```

So why that message? I never had it before.

(Sry. i'm not a developer of that product, so it's hard to find the responsible code...)

With kind regards,
Jan

**Comment by jayjupdhig** [comment]
No anwser??

**Comment by fraschbi** [comment]
Hi @jayjupdhig,

This exception suggests that there is not enough disc space available.
How much free disk space do you have available?

Regards,
Florian

**Comment by jayjupdhig** [comment]
Hi Florian

Oh - thank you very much for your feedback. :-)

Yes, that may be the reason - there was i time (before i've done a cleanup) with a very very small amount of free hd space.

If it occurs again, i will check the free space first!


With best regards from Switzerland,
Jan
