### ISSUE TITLE
When integrate SpringBoot and kafka client into the extension,an exception has been throwed

### ISSUE THREAD

**Issue by kexianjun** [hivemq/hivemq-community-edition#22]
when receiveed a kafka message in my extension module, and I want to send this message using 
```
Services.publishService().publish
```
## Expected behavior
it's work
## Actual behavior
java.lang.RuntimeException: Static class Builders cannot be called from a thread "kafkaMessageListenerContainer-C-1" which does not have a HiveMQ extension classloader as its context classloader.
	at com.hivemq.extension.sdk.api.services.builder.Builders.getClassSupplier(Builders.java:98)
	at com.hivemq.extension.sdk.api.services.builder.Builders.publish(Builders.java:67)
	at com.hivemq.extension.sdk.api.services.publish.Publish.builder(Publish.java:47)
	at com.caocao.hivemq.extension.kafka.TestHandler.handle(TestHandler.java:39)
	at com.caocao.hivemq.extension.kafka.KafkaMessageListener.onMessage(KafkaMessageListener.java:79)
	at com.caocao.hivemq.extension.kafka.KafkaMessageListener.onMessage(KafkaMessageListener.java:40)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:1278)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:1256)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:1217)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:1198)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:1118)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:933)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:749)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:698)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.lang.Thread.run(Thread.java:834)
## Details
- Affected HiveMQ CE version(s): 
- Used JVM version:

**Comment by sauroter** [comment]
Hi @kexianjun,

nice to see your interest in the development of HiveMQ - Community Edition extensions.

We already offer a full fledged HiveMQ [Enterprise Extension for Kafka](https://www.hivemq.com/extension/hivemq-kafka-extension/), if you are interested.

To the issue at hand:
Looks like you ran afoul of the extension isolation feature. The ClientService needs to be initialized from a special classloader context.

Try doing something like this:
````
public class MyExtensionMain implements ExtensionMain {

    public static @Nullable ClientService clientService;

    @Override
    public void extensionStart(final @NotNull ExtensionStartInput extensionStartInput, 
                               final @NotNull ExtensionStartOutput extensionStartOutput) {
        clientService = Services.clientService();
    }
    
    @Override
    public void extensionStop(final @NotNull ExtensionStopInput extensionStopInput,
                              final @NotNull ExtensionStopOutput extensionStopOutput) {
    }
}
````
And then accessing the ClientService over the static context, or get yourself an instance and inject it via Spring.

Have a good day
Georg

**Comment by kexianjun** [comment]
Thx, by following your tips, it works fine for me now.
