### ISSUE TITLE
Why the memory usage is too large and the limit does not work？

### ISSUE THREAD

**Issue by yilezhu** [hivemq/hivemq-community-edition#274]
## Expected behavior
Memory is limited, memory usage is not that large

## Actual behavior
As shown in the figure below, the memory consumption is too large and is increasing all the time. In fact, I only have a small number of clients sending data in groups every five minutes!
![image](https://user-images.githubusercontent.com/18655233/119447730-e7e63300-bd62-11eb-95de-09078ce127e1.png)
The specific startup parameters are as follows：
![image](https://user-images.githubusercontent.com/18655233/119447864-195efe80-bd63-11eb-830f-7ccef060e1d3.png)

`-Xmx1536m -XX:MaxDirectMemorySize=1g `

I checked the data directory, and the disk space is as follows.
![image](https://user-images.githubusercontent.com/18655233/119448312-ba4db980-bd63-11eb-8b75-88116c9394fd.png)

In addition, I used JProfiler to check the memory usage, as shown below：
Heap
![image](https://user-images.githubusercontent.com/18655233/119448577-1dd7e700-bd64-11eb-903a-17873fd89220.png)
Non-Heap
![image](https://user-images.githubusercontent.com/18655233/119448612-28927c00-bd64-11eb-91d1-6e1a171069b1.png)

### Steps
Add the following configuration to the startup parameters ‘-Xmx1536m -XX:MaxDirectMemorySize=1g’ .But it still takes up nearly 5g of memory
## Details
- Affected HiveMQ CE version(s): 2021.1
- Used JVM version: java11

**Comment by DC2-DanielKrueger** [comment]
Hallo @yilezhu,

We had cases, where memory mapped files from Xodus took large parts of the memory. It was fixed with this commit: https://github.com/hivemq/hivemq-community-edition/commit/f5f2687a770b53b34afb13ec462b95323d3a4b82. However unfortunetly there was no release since then. 

I did not find an easy way to get a metric how much memory is used by memory mapped files. One approach could be to use visualvm with this plugin: https://blogs.oracle.com/nbprofiler/new-plugin-for-visualvm-buffer-monitor. 

Best regards, 
Daniel

**Comment by yilezhu** [comment]
Hello, @DC2-DanielKrueger . Do you know the latest release plan?If it takes a long time to release, I have to download the source code and compile it manually.

**Comment by DC2-DanielKrueger** [comment]
Yeah, unfortunetly the memory mapped files can grow incredible big, thats why we deactivate them. 
Regarding the release - I need to ask. Will update you on this.

**Comment by yilezhu** [comment]
Thank you. Can I use this version to get the latest release package temporarily! https://hivemq.github.io/nightly-builds/#dependency-block

**Comment by DC2-DanielKrueger** [comment]
Yeah, you can use it, would suggest to use the current master branch.

**Comment by yilezhu** [comment]
Thank you very much. I will use it and keep watching. If there is no problem, I will turn off the issue.

**Comment by yilezhu** [comment]
I have tested, but there is still a problem of continuous memory growth. I have limited the memory and it doesn't seem to work!
`JAVA_OPTS="$JAVA_OPTS -Xms1536m -Xmx1536m -XX:MaxDirectMemorySize=1g"`
![image](https://user-images.githubusercontent.com/18655233/120255626-fbdbe880-c2be-11eb-9b73-605ea94c958f.png)
![image](https://user-images.githubusercontent.com/18655233/120255691-25950f80-c2bf-11eb-8fbc-814a45e8dd2b.png)

**Comment by DC2-DanielKrueger** [comment]
Ok, so the RSS shows more than just the Java Heap and the DirectMemory. It also includes the native memory libraries use - in our case RocksDB, a database framework for persistence. For testing you could set persistence to in-memory:

```
<hivemq>
.......

<!--> other configs you might have changed <!-->
.......
  <persistence>
    <mode>in-memory</mode>
  </persistence>
</hivemq>
```

**Comment by yilezhu** [comment]
Do you mean persistence in memory? Does that mean more memory?

**Comment by DC2-DanielKrueger** [comment]
Depending on your concrete HiveMQ usage - perhaps yes. If you have Queued Messages their payloads will then be in memory f.e..

**Comment by DC2-DanielKrueger** [comment]
Usually we recommend splitting the complete memory on half and setting he heap to use exact one half. The Other half is used by native libraries like RocksDB.

**Comment by yilezhu** [comment]
Here is my configuration.There should be no problem
`
<hivemq>

    <listeners>
        <tcp-listener>
            <port>1883</port>
            <bind-address>0.0.0.0</bind-address>
        </tcp-listener>
    </listeners>
    <mqtt>
        <queued-messages>
            <max-queue-size>100000</max-queue-size>
            <strategy>discard-oldest</strategy>
        </queued-messages>

        <topic-alias>
            <enabled>true</enabled>
            <max-per-client>10</max-per-client>
        </topic-alias>

        <message-expiry>
            <max-interval>2592000</max-interval> 
        </message-expiry>

        <session-expiry>
            <max-interval>604800</max-interval> 

        </session-expiry>

        <keep-alive>
            <allow-unlimited>false</allow-unlimited>
            <max-keep-alive>65535</max-keep-alive>
        </keep-alive>

        <packets>
            <max-packet-size>268435460</max-packet-size> 
        </packets>

        <receive-maximum>
            <server-receive-maximum>1000</server-receive-maximum>
        </receive-maximum>

        <quality-of-service>
            <max-qos>2</max-qos>
        </quality-of-service>

        <wildcard-subscriptions>
            <enabled>true</enabled>
        </wildcard-subscriptions>

        <shared-subscriptions>
            <enabled>true</enabled>
        </shared-subscriptions>

        <subscription-identifier>
            <enabled>true</enabled>
        </subscription-identifier>

        <retained-messages>
            <enabled>true</enabled>
        </retained-messages>

    </mqtt>
</hivemq>
`

**Comment by DC2-DanielKrueger** [comment]
Ok looks fine, so I see two options:

1. Setting Max Heap to half of the amount of the memory you want HiveMQ to use.
2. Usage of in-memory persistences via the config option from above

**Comment by yilezhu** [comment]
OK, you mean to use memory for persistence. Does that mean that when broker stops abnormally, data will be lost?

**Comment by DC2-DanielKrueger** [comment]
Yeah exactly, its not persistent on disc, only in memory. So if this is not an option, then go for the first idea and limit the heap to the half of the memory that hivemq should use max.

**Comment by yilezhu** [comment]
Thank you for your patient reply, I will try and look forward to the results

**Comment by yilezhu** [comment]
Failed, memory is still increasing slowly. 
JAVA_OPTS="$JAVA_OPTS -Xms1536m -Xmx1536m -XX:MaxDirectMemorySize=1g"
But the memory is still up to 3.2g

**Comment by DC2-DanielKrueger** [comment]
What is your limit for Memory Usage? 3G? I would lower the heap a bit again and let it run for a while and check if its within your memory budget.:

JAVA_OPTS="$JAVA_OPTS -Xms1400m -Xmx1400m -XX:MaxDirectMemorySize=500m"

**Comment by yilezhu** [comment]
In fact, I want to limit it to about 2.5G. Yesterday, I made a mistake, and then the broker couldn't get up. The mistake is as follows:
``` 
2021-06-02 22:04:43,552 ERROR - Exception in shared publishes poll handling for client HandleData_Mqtt_Client_0for shared subscription HandleData/cascade/client/status/report
jetbrains.exodus.log.DataCorruptionException: CompoundByteIterator: no more bytes available, address = 11590836, file = 00000000000.xd
	at jetbrains.exodus.log.DataCorruptionException.raise(DataCorruptionException.java:33)
	at jetbrains.exodus.log.CompoundByteIterator.next(CompoundByteIterator.java:65)
	at jetbrains.exodus.log.CompressedUnsignedLongByteIterable.getInt(CompressedUnsignedLongByteIterable.java:94)
	at jetbrains.exodus.tree.patricia.ImmutableNode.extractLazyIterable(ImmutableNode.java:213)
	at jetbrains.exodus.tree.patricia.ImmutableNode.extractValue(ImmutableNode.java:208)
	at jetbrains.exodus.tree.patricia.ImmutableNode.<init>(ImmutableNode.java:48)
	at jetbrains.exodus.tree.patricia.ImmutableNode.<init>(ImmutableNode.java:41)
	at jetbrains.exodus.tree.patricia.PatriciaTreeBase.loadNode(PatriciaTreeBase.java:132)
	at jetbrains.exodus.tree.patricia.ChildReference.getNode(ChildReference.java:43)
	at jetbrains.exodus.tree.patricia.PatriciaTraverser.moveDown(PatriciaTraverser.java:71)
	at jetbrains.exodus.tree.TreeCursor.moveToNext(TreeCursor.java:201)
	at jetbrains.exodus.tree.TreeCursor.getNext(TreeCursor.java:68)
	at jetbrains.exodus.env.CursorImpl.getNext(CursorImpl.java:48)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.compareNextClientId(ClientQueueXodusLocalPersistence.java:1088)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.skipPrefix(ClientQueueXodusLocalPersistence.java:1071)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.iterateQueue(ClientQueueXodusLocalPersistence.java:1119)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.lambda$readNew$7(ClientQueueXodusLocalPersistence.java:606)
	at jetbrains.exodus.env.EnvironmentImpl.computeInTransaction(EnvironmentImpl.java:1022)
	at jetbrains.exodus.env.EnvironmentImpl.computeInExclusiveTransaction(EnvironmentImpl.java:282)
	at jetbrains.exodus.env.ContextualEnvironmentImpl.computeInExclusiveTransaction(ContextualEnvironmentImpl.java:158)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.readNew(ClientQueueXodusLocalPersistence.java:597)
	at com.hivemq.persistence.clientqueue.ClientQueuePersistenceImpl.lambda$readNew$3(ClientQueuePersistenceImpl.java:200)
	at com.hivemq.persistence.ProducerQueuesImpl.execute(ProducerQueuesImpl.java:202)
	at com.hivemq.persistence.SingleWriterServiceImpl$SingleWriterTask.run(SingleWriterServiceImpl.java:315)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-02 22:04:43,624 ERROR - Could not put a payload because of an exception: 
org.rocksdb.RocksDBException: While appending to file: /ronds/hivemq-ce-2021.1/data/persistence/publish_payload_store/040500_R/publish_payload_store_4/000769.log: 设备上没有空间
	at org.rocksdb.RocksDB.put(Native Method)
	at org.rocksdb.RocksDB.put(RocksDB.java:716)
	at com.hivemq.persistence.payload.PublishPayloadRocksDBLocalPersistence.put(PublishPayloadRocksDBLocalPersistence.java:131)
	at com.hivemq.persistence.payload.PublishPayloadPersistenceImpl.lambda$add$0(PublishPayloadPersistenceImpl.java:119)
	at com.hivemq.persistence.payload.PublishPayloadPersistenceImpl.accessBucket(PublishPayloadPersistenceImpl.java:240)
	at com.hivemq.persistence.payload.PublishPayloadPersistenceImpl.add(PublishPayloadPersistenceImpl.java:108)
	at com.hivemq.mqtt.services.PublishDistributorImpl.createPublish(PublishDistributorImpl.java:180)
	at com.hivemq.mqtt.services.PublishDistributorImpl.queuePublish(PublishDistributorImpl.java:158)
	at com.hivemq.mqtt.services.PublishDistributorImpl.handlePublish(PublishDistributorImpl.java:148)
	at com.hivemq.mqtt.services.PublishDistributorImpl.sendMessageToSubscriber(PublishDistributorImpl.java:123)
	at com.hivemq.mqtt.services.PublishDistributorImpl.distributeToNonSharedSubscribers(PublishDistributorImpl.java:89)
	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at com.google.inject.internal.DelegatingInvocationHandler.invoke(DelegatingInvocationHandler.java:50)
	at com.sun.proxy.$Proxy42.distributeToNonSharedSubscribers(Unknown Source)
	at com.hivemq.mqtt.services.InternalPublishServiceImpl.deliverPublish(InternalPublishServiceImpl.java:175)
	at com.hivemq.mqtt.services.InternalPublishServiceImpl.handlePublish(InternalPublishServiceImpl.java:150)
	at com.hivemq.mqtt.services.InternalPublishServiceImpl.publish(InternalPublishServiceImpl.java:83)
	at com.hivemq.mqtt.handler.publish.IncomingPublishService.publishMessage(IncomingPublishService.java:224)
	at com.hivemq.mqtt.handler.publish.IncomingPublishService.authorizePublish(IncomingPublishService.java:157)
	at com.hivemq.mqtt.handler.publish.IncomingPublishService.processPublish(IncomingPublishService.java:125)
	at com.hivemq.extensions.handler.PluginAuthorizerServiceImpl.authorizePublish(PluginAuthorizerServiceImpl.java:121)
	at com.hivemq.extensions.handler.IncomingPublishHandler$PublishInboundInterceptorContext.run(IncomingPublishHandler.java:222)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-02 22:05:00,316 ERROR - Exception in shared publishes poll handling for client HandleData_Mqtt_Client_0for shared subscription HandleData/sys/thing/#
jetbrains.exodus.log.DataCorruptionException: CompoundByteIterator: no more bytes available, address = 134922262, file = 00000000000.xd
	at jetbrains.exodus.log.DataCorruptionException.raise(DataCorruptionException.java:33)
	at jetbrains.exodus.log.CompoundByteIterator.next(CompoundByteIterator.java:65)
	at jetbrains.exodus.log.CompressedUnsignedLongByteIterable.getInt(CompressedUnsignedLongByteIterable.java:94)
	at jetbrains.exodus.tree.patricia.ImmutableNode.extractLazyIterable(ImmutableNode.java:213)
	at jetbrains.exodus.tree.patricia.ImmutableNode.extractValue(ImmutableNode.java:208)
	at jetbrains.exodus.tree.patricia.ImmutableNode.<init>(ImmutableNode.java:48)
	at jetbrains.exodus.tree.patricia.ImmutableNode.<init>(ImmutableNode.java:41)
	at jetbrains.exodus.tree.patricia.PatriciaTreeBase.loadNode(PatriciaTreeBase.java:132)
	at jetbrains.exodus.tree.patricia.ChildReference.getNode(ChildReference.java:43)
	at jetbrains.exodus.tree.patricia.PatriciaTraverser.moveToRange(PatriciaTraverser.java:300)
	at jetbrains.exodus.tree.TreeCursor.moveTo(TreeCursor.java:187)
	at jetbrains.exodus.tree.TreeCursor.getSearchKeyRange(TreeCursor.java:148)
	at jetbrains.exodus.env.CursorImpl.getSearchKeyRange(CursorImpl.java:110)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.iterateQueue(ClientQueueXodusLocalPersistence.java:1113)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.lambda$readNew$7(ClientQueueXodusLocalPersistence.java:606)
	at jetbrains.exodus.env.EnvironmentImpl.computeInTransaction(EnvironmentImpl.java:1022)
	at jetbrains.exodus.env.EnvironmentImpl.computeInExclusiveTransaction(EnvironmentImpl.java:282)
	at jetbrains.exodus.env.ContextualEnvironmentImpl.computeInExclusiveTransaction(ContextualEnvironmentImpl.java:158)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.readNew(ClientQueueXodusLocalPersistence.java:597)
	at com.hivemq.persistence.clientqueue.ClientQueuePersistenceImpl.lambda$readNew$3(ClientQueuePersistenceImpl.java:200)
	at com.hivemq.persistence.ProducerQueuesImpl.execute(ProducerQueuesImpl.java:202)
	at com.hivemq.persistence.SingleWriterServiceImpl$SingleWriterTask.run(SingleWriterServiceImpl.java:315)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-02 22:05:00,316 ERROR - Exception in shared publishes poll handling for client HandleData_Mqtt_Client_0for shared subscription HandleData/cascade/client/status/report
jetbrains.exodus.log.DataCorruptionException: CompoundByteIterator: no more bytes available, address = 11590836, file = 00000000000.xd
	at jetbrains.exodus.log.DataCorruptionException.raise(DataCorruptionException.java:33)
	at jetbrains.exodus.log.CompoundByteIterator.next(CompoundByteIterator.java:65)
	at jetbrains.exodus.log.CompressedUnsignedLongByteIterable.getInt(CompressedUnsignedLongByteIterable.java:94)
	at jetbrains.exodus.tree.patricia.ImmutableNode.extractLazyIterable(ImmutableNode.java:213)
	at jetbrains.exodus.tree.patricia.ImmutableNode.extractValue(ImmutableNode.java:208)
	at jetbrains.exodus.tree.patricia.ImmutableNode.<init>(ImmutableNode.java:48)
	at jetbrains.exodus.tree.patricia.ImmutableNode.<init>(ImmutableNode.java:41)
	at jetbrains.exodus.tree.patricia.PatriciaTreeBase.loadNode(PatriciaTreeBase.java:132)
	at jetbrains.exodus.tree.patricia.ChildReference.getNode(ChildReference.java:43)
	at jetbrains.exodus.tree.patricia.PatriciaTraverser.moveDown(PatriciaTraverser.java:71)
	at jetbrains.exodus.tree.TreeCursor.moveToNext(TreeCursor.java:201)
	at jetbrains.exodus.tree.TreeCursor.getNext(TreeCursor.java:68)
	at jetbrains.exodus.env.CursorImpl.getNext(CursorImpl.java:48)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.compareNextClientId(ClientQueueXodusLocalPersistence.java:1088)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.skipPrefix(ClientQueueXodusLocalPersistence.java:1071)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.iterateQueue(ClientQueueXodusLocalPersistence.java:1119)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.lambda$readNew$7(ClientQueueXodusLocalPersistence.java:606)
	at jetbrains.exodus.env.EnvironmentImpl.computeInTransaction(EnvironmentImpl.java:1022)
	at jetbrains.exodus.env.EnvironmentImpl.computeInExclusiveTransaction(EnvironmentImpl.java:282)
	at jetbrains.exodus.env.ContextualEnvironmentImpl.computeInExclusiveTransaction(ContextualEnvironmentImpl.java:158)
	at com.hivemq.persistence.clientqueue.ClientQueueXodusLocalPersistence.readNew(ClientQueueXodusLocalPersistence.java:597)
	at com.hivemq.persistence.clientqueue.ClientQueuePersistenceImpl.lambda$readNew$3(ClientQueuePersistenceImpl.java:200)
	at com.hivemq.persistence.ProducerQueuesImpl.execute(ProducerQueuesImpl.java:202)
	at com.hivemq.persistence.SingleWriterServiceImpl$SingleWriterTask.run(SingleWriterServiceImpl.java:315)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-02 22:05:38,971 ERROR - Exception on Log recovery. Approved high address = 4116
jetbrains.exodus.ExodusException: Can't read loggable fully, address = 8806, file = 00000000000.xd
	at jetbrains.exodus.log.Log.<init>(Log.java:151)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
	at com.hivemq.persistence.local.xodus.XodusLocalPersistence.lambda$start$2(XodusLocalPersistence.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-06-02 22:05:39,086 ERROR - Exception on Log recovery. Approved high address = 134731819
jetbrains.exodus.ExodusException: Can't read loggable fully, address = 134932192, file = 00000000000.xd
	at jetbrains.exodus.log.Log.<init>(Log.java:151)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:137)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:115)
	at jetbrains.exodus.env.Environments.newLogInstance(Environments.java:104)
	at jetbrains.exodus.env.Environments.newContextualInstance(Environments.java:94)
	at com.hivemq.persistence.local.xodus.XodusLocalPersistence.lambda$start$2(XodusLocalPersistence.java:154)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by yilezhu** [comment]
@DC2-DanielKrueger Hello, friend, is there any good tool to check the queue in the broker?

**Comment by fraschbi** [comment]
Hi @yilezhu,

GitHub issues are meant to report issues with the HiveMQ Community Edition.
If you have general questions like your last one, please refer to the [HiveMQ Community Forum](http://community.hivemq.com/).

Thanks,
Florian

**Comment by yilezhu** [comment]
Sorry, I'll do that. I'll delete that comment

**Comment by DC2-DanielKrueger** [comment]
The Xodus exception indicates some failure when reading the database. Please open another issue, if this problem continues to show up. 

If you want to limit the memory to about 2,5GB. I would limit Heap to around 1GB and look how the broker behaves. A small heap may have negative influence depending on many factors, like publish rate, connected clients, queues, and so on. You can not predict that without knowing the exact use case tbh. Testing it is the way forward. 

Best regards, 
Daniel

**Comment by yilezhu** [comment]
Thank you very much for your reply. I will close this problem. The current practice is to deploy broker independently without memory limitation.
