### ISSUE TITLE
broker doesn't start CENTOS 7 X64 , OPENJDK 11

### ISSUE THREAD

**Issue by mbravo1** [hivemq/hivemq-community-edition#283]
**When starting an broker on the current version 11 of OPENJDK with sudo ./run.sh. Broker doesn't start, SO is CENTOS 7 x64 , and send the next errors:**

```
2021-05-27 10:50:51,425 DEBUG  [main] [com.hivemq.configuration.service.impl.SecurityConfigurationServiceImpl] >> Setting allow server assigned client identifier to true
2021-05-27 10:50:51,426 DEBUG  [main] [com.hivemq.configuration.service.impl.SecurityConfigurationServiceImpl] >> Setting validate UTF-8 to true
2021-05-27 10:50:51,426 DEBUG  [main] [com.hivemq.configuration.service.impl.SecurityConfigurationServiceImpl] >> Setting payload format validation to false
2021-05-27 10:50:51,426 DEBUG  [main] [com.hivemq.configuration.service.impl.SecurityConfigurationServiceImpl] >> Setting allow-problem-information to true
2021-05-27 10:50:51,426 DEBUG  [main] [com.hivemq.statistics.UsageStatisticsConfigImpl] >> Setting anonymous usage statistics enabled to false
2021-05-27 10:50:51,430 INFO   [main] [com.hivemq.HiveMQServer] >> This HiveMQ ID is GrLef
2021-05-27 10:50:51,453 INFO   [main] [migrations] >> Checking for migrations (HiveMQ version 2021.1).
2021-05-27 10:50:51,459 INFO   [main] [migrations] >> Read metadata file: MetaInformation{hivemqVersion='2021.1', clientSessionPersistenceVersion='040000', queuedMessagesPersistenceVersion='040500', subscriptionPersistenceVersion='040000', retainedMessagesPersistenceVersion='040500_R', publishPayloadPersistenceVersion='040500_R', retainedMessagesPersistenceType='FILE_NATIVE', publishPayloadPersistenceType='FILE_NATIVE'}
2021-05-27 10:50:51,509 INFO   [main] [migrations] >> Nothing to migrate found.
2021-05-27 10:50:51,509 INFO   [main] [migrations] >> Checking for value migrations (HiveMQ version 2021.1).
2021-05-27 10:50:51,509 INFO   [main] [migrations] >> Read metadata file: MetaInformation{hivemqVersion='2021.1', clientSessionPersistenceVersion='040000', queuedMessagesPersistenceVersion='040500', subscriptionPersistenceVersion='040000', retainedMessagesPersistenceVersion='040500_R', publishPayloadPersistenceVersion='040500_R', retainedMessagesPersistenceType='FILE_NATIVE', publishPayloadPersistenceType='FILE_NATIVE'}
2021-05-27 10:50:51,509 INFO   [main] [migrations] >> Nothing to migrate found.
**_2021-05-27 10:50:52,389 ERROR  [main] [com.hivemq.bootstrap.HiveMQExceptionHandlerBootstrap] >> Uncaught Error:
java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni17450628653984656422.so: /tmp/librocksdbjni17450628653984656422.so: failed to map segment from shared object: Operation not permitted_**
        at java.base/java.lang.ClassLoader$NativeLibrary.load0(Native Method)
        at java.base/java.lang.ClassLoader$NativeLibrary.load(ClassLoader.java:2442)
        at java.base/java.lang.ClassLoader$NativeLibrary.loadLibrary(ClassLoader.java:2498)
        at java.base/java.lang.ClassLoader.loadLibrary0(ClassLoader.java:2694)
        at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2627)
        at java.base/java.lang.Runtime.load0(Runtime.java:768)
        at java.base/java.lang.System.load(System.java:1837)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:79)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:57)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:67)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:38)
        at org.rocksdb.FlushOptions.<clinit>(FlushOptions.java:14)
        at com.hivemq.persistence.payload.PublishPayloadRocksDBLocalPersistence.<clinit>(PublishPayloadRocksDBLocalPersistence.java:48)
        at com.hivemq.persistence.payload.PublishPayloadRocksDBLocalPersistence$$FastClassByGuice$$bfd4a565.newInstance(<generated>)
        at com.google.inject.internal.DefaultConstructionProxyFactory$FastClassProxy.newInstance(DefaultConstructionProxyFactory.java:89)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:114)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:42)
        at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:65)
        at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:113)
        at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:91)
        at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:306)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:62)
        at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
        at com.google.inject.internal.SingletonScope$1.get(SingletonScope.java:168)
        at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:39)
        at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:213)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:184)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:111)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.hivemq.bootstrap.ioc.GuiceBootstrap.persistenceInjector(GuiceBootstrap.java:142)
        at com.hivemq.HiveMQServer.main(HiveMQServer.java:139)
```

**Comment by FinnHMQ** [comment]
Hey Miguel,

it looks like the system user executing HiveMQ does not have the necessary permissions to write to /tmp/.
This has become necessary with [HiveMQ 4.3](https://www.hivemq.com/docs/hivemq/4.6/user-guide/system-requirements.html#os).

**Comment by mbravo1** [comment]
Hello.

Thank you very much for answering.

I am running as root for the quick test of this version, the root user has all the permissions. However, the same thing happens to me with the hivemq user.

> sudo ./run.sh

I see that the same thing has happened to other user.

[https://groups.google.com/g/rocksdb/c/cjeAK00NzO0](url)

> [cermig@localhost]$ ls -la


> drwxrwxrwt.  10 root root  4096 Jun 29 11:29 tmp

Thanks !!
