### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by pspburner** [hivemq/hivemq-community-edition#338]
## Expected behavior
Over 4000 clients connet to broker at the same time.

## Actual behavior
It throws IOExeption.

2022-05-23 21:51:42,485 WARN  - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
java.io.IOException: Too many open files
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:533)
        at java.base/sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:285)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:119)
        at io.netty.util.internal.SocketUtils$5.run(SocketUtils.java:116)
        at java.base/java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.accept(SocketUtils.java:116)
        at io.netty.channel.socket.nio.NioServerSocketChannel.doReadMessages(NioServerSocketChannel.java:147)
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:79)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:719)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:655)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)

### Steps
1. Run HiveMQ on CentOS 7
2. Test MQTT connection with [plugin of JMeter](https://github.com/emqx/mqtt-jmeter)
![image](https://user-images.githubusercontent.com/40882419/169757209-db5b3760-2e1a-4666-9a14-ddcecc384d70.png)
![image](https://user-images.githubusercontent.com/40882419/169754130-4268f0d2-51ff-40f8-b56d-588e742e4284.png)
![image](https://user-images.githubusercontent.com/40882419/169755336-21c6fb3b-4db6-4a24-bdb5-32573463ef25.png)

## Details
- Affected HiveMQ CE version(s): 2021.3
- Used JVM version:11.0.15

**Comment by pspburner** [comment]
> Hello @pspburner, this is most likely a OS issue, please make sure that your file limit is adapted. You can find the docu for adapting the OS limits here: https://github.com/hivemq/hivemq-community-edition/wiki/System-Requirements#linux-configuration-optimizations

Yes. This method works. It also uses command of ulimit to modify the file limit temporarily. Thanks a lot!
