### ISSUE TITLE
Broker does not start after the installation in Ubuntu

### ISSUE THREAD

**Issue by nobso** [hivemq/hivemq-community-edition#348]
## Expected behavior
HiveMQ Community Edition Server starts successfully

## Actual behavior
HiveMQ Community Edition Server does not start

### Steps
Followed steps from https://github.com/hivemq/hivemq-community-edition/wiki/Installing-HiveMQ#installation-on-unix-based-systems-linux-bsd-macos-x-unix 

## Details
- Affected HiveMQ CE version(s):  2022.2-SNAPSHOT
- Used JVM version: JAVA_VERSION: 11

`
-------------------------------------------------------------------------

  HiveMQ Start Script for Linux/Unix v1.13

-------------------------------------------------------------------------

  HIVEMQ_HOME: /opt/hivemq

  JAVA_OPTS:  -Djava.net.preferIPv4Stack=true --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED --add-opens java.base/sun.nio.ch=ALL-UNNAMED --add-opens jdk.management/com.sun.management.internal=ALL-UNNAMED --add-exports java.base/jdk.internal.misc=ALL-UNNAMED -Djava.security.egd=file:/dev/./urandom -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9010 -Dcom.sun.management.jmxremote.local.only=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -XX:+CrashOnOutOfMemoryError -XX:+HeapDumpOnOutOfMemoryError

  JAVA_VERSION: 11

-------------------------------------------------------------------------

2022-09-01 05:59:40,369 INFO  - Starting HiveMQ Community Edition Server
2022-09-01 05:59:40,371 INFO  - HiveMQ version: 2022.2-SNAPSHOT
2022-09-01 05:59:40,371 INFO  - HiveMQ home directory: /opt/hivemq
2022-09-01 05:59:40,372 INFO  - Log Configuration was overridden by /opt/hivemq/conf/logback.xml
2022-09-01 05:59:40,648 INFO  - This HiveMQ ID is FDjBH
2022-09-01 05:59:42,124 INFO  - Starting with file persistence mode.
2022-09-01 05:59:42,732 INFO  - Starting HiveMQ extension system.
2022-09-01 05:59:42,775 WARN  -
################################################################################################################
# This HiveMQ deployment is not secure! You are lacking Authentication and Authorization.                      #
# Right now any MQTT client can connect to the broker with a full set of permissions.                          #
# For production usage, add an appropriate security extension and remove the hivemq-allow-all extension.       #
# You can download security extensions from the HiveMQ Marketplace (https://www.hivemq.com/extensions/).       #
################################################################################################################
2022-09-01 05:59:42,778 INFO  - Extension "Allow All Extension" version 1.0.0 started successfully.
2022-09-01 05:59:42,810 INFO  - Starting TCP listener on address 0.0.0.0 and port 1883
2022-09-01 05:59:42,844 WARN  - An exception was thrown by com.hivemq.bootstrap.HiveMQNettyBootstrap$UpdateGivenFutureListener.operationComplete()
java.lang.NullPointerException: null
        at com.hivemq.bootstrap.HiveMQNettyBootstrap$UpdateGivenFutureListener.operationComplete(HiveMQNettyBootstrap.java:244)
        at com.hivemq.bootstrap.HiveMQNettyBootstrap$UpdateGivenFutureListener.operationComplete(HiveMQNettyBootstrap.java:228)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:552)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:609)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:117)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.safeSetFailure(AbstractChannel.java:999)
        at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:564)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:506)
        at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:491)
        at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
        at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
        at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
        at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
        at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)`

**Comment by nobso** [comment]
I did try a fresh install in the bare metal box, it works now.
