### ISSUE TITLE
Prometheus extension not working

### ISSUE THREAD

**Issue by jens1000** [hivemq/hivemq-community-edition#39]
## Actual behavior

Starting the broker with the prometheus extension results in this error log:

```
2019-07-24 13:19:57,125 INFO  - Starting HiveMQ Community Edition Server
2019-07-24 13:19:57,127 INFO  - HiveMQ version: 2019.1
2019-07-24 13:19:57,127 INFO  - HiveMQ home directory: /opt/hivemq
2019-07-24 13:19:57,162 INFO  - Log Configuration was overridden by /opt/hivemq/conf/logback.xml
2019-07-24 13:19:57,356 INFO  - This HiveMQ ID is mwDbQ
2019-07-24 13:20:14,353 INFO  - Created user preferences directory.
2019-07-24 13:20:14,873 INFO  - Starting HiveMQ extension system.
2019-07-24 13:20:14,925 INFO  - Starting TCP listener on address 0.0.0.0 and port 1883
2019-07-24 13:20:14,998 INFO  - Started TCP Listener on address 0.0.0.0 and on port 1883
2019-07-24 13:20:14,999 INFO  - Started HiveMQ in 17877ms
2019-07-24 13:20:15,040 ERROR - Extension with id "hivemq-prometheus-extension" cannot be started because of an uncaught exception thrown by the extension. Extension will be disabled.
java.lang.NoClassDefFoundError: javax/servlet/ServletContextListener
        at org.eclipse.jetty.server.handler.ContextHandler.<clinit>(ContextHandler.java:114)
        at com.hivemq.extensions.prometheus.export.PrometheusServer.start(PrometheusServer.java:64)
        at com.hivemq.extensions.prometheus.PrometheusMainClass.extensionStart(PrometheusMainClass.java:65)
        at com.hivemq.extensions.HiveMQExtensionImpl.start(HiveMQExtensionImpl.java:133)
        at com.hivemq.extensions.HiveMQPlugins.pluginStart(HiveMQPlugins.java:209)
        at com.hivemq.extensions.loader.PluginLifecycleHandlerImpl.lambda$startPlugin$0(PluginLifecycleHandlerImpl.java:82)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: javax.servlet.ServletContextListener
        at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
        at com.hivemq.extensions.classloader.IsolatedPluginClassloader.loadClass(IsolatedPluginClassloader.java:123)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 9 common frames omitted
```

### Steps
* Download the broker from [https://github.com/hivemq/hivemq-community-edition/releases/download/2019.1/hivemq-ce-2019.1.zip](https://github.com/hivemq/hivemq-community-edition/releases/download/2019.1/hivemq-ce-2019.1.zip)
* Download the extension from [https://www.hivemq.com/releases/extensions/hivemq-prometheus-extension-4.0.1.zip](https://www.hivemq.com/releases/extensions/hivemq-prometheus-extension-4.0.1.zip)
* Unzip both
* Move extension to extension directory
* run run.sh

## Details
- Affected HiveMQ CE version(s): 
- Used JVM version: OpenJDK 11

## Solution
I could solve this issue by downloading the broker source code and add this dependency to the javax section in the build.gradle file:
`[group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'],`

Then compile it and use the precompiled prometheus extension from the marketplace.
After that the extension seems to be working.

**Comment by fraschbi** [comment]
Hi @jens1000,

thank you for this detailed description.
I tagged this as a bug and we will fix it with one of our upcoming new releases.
If you want to, you are happy to provide a PullRequest, provided you follow our [Contribution Guidelines](https://github.com/hivemq/hivemq-community-edition/blob/master/CONTRIBUTING.adoc).

Kind regards,
Florian

**Comment by MicWalter** [comment]
@fraschbi @jens1000 It seems with then new Prometheus extension version (4.0.2) this was fixed.

I also tested it and it works now, so I think this issue can be closed.

Regards,
Michael

**Comment by MicWalter** [comment]
I'm closing this issue.
