### ISSUE TITLE
MQTT CLI cannot consume queued messages in persistant session

### ISSUE THREAD

**Issue by Zuendelmeister** [hivemq/hivemq-community-edition#442]
## Expected behavior
After reopening a persistant session the MQTT CLI client should process all queued data.
## Actual behavior
The first queued message will be processed and then an error happens:
`io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: [What's different in 2.0 · ReactiveX/RxJava Wiki · GitHub 1](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) | java.lang.UnsupportedOperationException: A publish must not be acknowledged if manual acknowledgement is not enabled
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException: A publish must not be acknowledged if manual acknowledgement is not enabled
at com.hivemq.client.internal.mqtt.message.publish.MqttPublish.acknowledge(MqttPublish.java:170)
at com.hivemq.cli.mqtt.SubscribeMqtt5PublishCallback.accept(SubscribeMqtt5PublishCallback.java:85)
at com.hivemq.cli.mqtt.SubscribeMqtt5PublishCallback.accept(SubscribeMqtt5PublishCallback.java:33)
at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303)
at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288)
at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
… 6 more
Exception in thread “RxComputationThreadPool-1” io.reactivex.exceptions.UndeliverableException: The exception could not be delivered to the consumer because it has already canceled/disposed the flow or the exception has nowhere to go to begin with. Further reading: [What's different in 2.0 · ReactiveX/RxJava Wiki · GitHub 1](https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling) | java.lang.UnsupportedOperationException: A publish must not be acknowledged if manual acknowledgement is not enabled
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:69)
at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.UnsupportedOperationException: A publish must not be acknowledged if manual acknowledgement is not enabled
at com.hivemq.client.internal.mqtt.message.publish.MqttPublish.acknowledge(MqttPublish.java:170)
at com.hivemq.cli.mqtt.SubscribeMqtt5PublishCallback.accept(SubscribeMqtt5PublishCallback.java:85)
at com.hivemq.cli.mqtt.SubscribeMqtt5PublishCallback.accept(SubscribeMqtt5PublishCallback.java:33)
at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:303)
at com.hivemq.client.internal.mqtt.MqttAsyncClient$CallbackSubscriber.onNext(MqttAsyncClient.java:288)
at io.reactivex.internal.operators.flowable.FlowableObserveOn$ObserveOnSubscriber.runAsync(FlowableObserveOn.java:407)
at io.reactivex.internal.operators.flowable.FlowableObserveOn$BaseObserveOnSubscriber.run(FlowableObserveOn.java:176)
at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)`

### Steps
2 MQTT CLI Clients. 1.: Subscriber, 2.: Publisher
1.: Opens a persistant session
`mqtt sub -t testtopic -q 1 --no-cleanStart -i testclient -h 127.0.0.1 --sessionExpiryInterval 3600`
2.: Sends data
`mqtt pub -t sendertopic -m ‘test3’ -q 1`
1.: kills session via ^C
2.: Keeps sending Data
1.: reconnects
`mqtt sub -t testtopic -q 1 --no-cleanStart -i testclient -h 127.0.0.1 --sessionExpiryInterval 3600`
After the reconnect, the first MQTT CLI Client consumes the first message und throws the error.

https://github.com/hivemq/hivemq-community-edition/assets/14317353/5587e256-e196-4f16-8003-276d730d104d

## Details

- Affected HiveMQ CE version(s):
MQTT CLI:
4.24.0
Picocli 4.7.0

- Used JVM version:
JVM: 11 (Oracle Corporation OpenJDK 64-Bit Server VM 11+28)

**Comment by Zuendelmeister** [comment]
Is there any idea what the problem is?

**Comment by LukasBrand** [comment]
Hello @Zuendelmeister,
there is an issue inside the MQTT-CLI where manual acknowledgment is enabled for publishes that are processed inside the subscription callback but not for publishes resulting from session resume during connect. 

I created a PR inside the MQTT-CLI repository: https://github.com/hivemq/mqtt-cli/pull/392 to fix this issue. It will be included into the upcoming MQTT-CLI release.
Thank you for reporting!
