### ISSUE TITLE
Install as Windows Service does not work, produces error

### ISSUE THREAD

**Issue by Terr4** [hivemq/hivemq-community-edition#460]
## Expected behavior
Following the instructions from https://docs.hivemq.com/hivemq/latest/user-guide/install-hivemq.html#windows to install HiveMQ as a service. Service should get registered in windows and running properly

## Actual behavior
Service gets registered properly but does not start.

`  HiveMQ Windows Service Install

"java" -Xmx30m -Djna_tmpdir="C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/../tmp" -Djava.net.preferIPv4Stack=true -jar "C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/../wrapper.jar" -i "C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/../conf/wrapper.conf"
YAJSW: yajsw-stable-12.12
OS   : Windows Server 2022/10.0/amd64
JVM  : Oracle Corporation/21.0.1/C:\Program Files\OpenJDK\jdk-21.0.1/64
Feb 12, 2024 4:54:23 PM org.apache.commons.vfs2.VfsLog info
INFO: Using "C:\Users\ADMUSR~1\AppData\Local\Temp\vfs_cache" as temporary files store.
************* INSTALLING HiveMQ ***********************

service cmd: java.exe -classpath "C:\Program Files\HiveMQ\HiveMQ\windows-service\wrapper.jar" -Xrs -Dwrapper.service=true "-Dwrapper.working.dir=C:\Program Files\HiveMQ\HiveMQ\bin" "-Djna_tmpdir=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/../tmp" "-Dwrapper_home=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/.." "-Dwrapper.config=C:\Program Files\HiveMQ\HiveMQ\windows-service\conf\wrapper.conf" -Dwrapper.additional.1x=-Xrs "-Djna_tmpdir=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\..\tmp" org.rzo.yajsw.boot.WrapperServiceBooter
Service HiveMQ installed
Press any key to continue . . .`

Windows reports it does not start, when executing the command manually I get following output:

`java.exe -classpath "C:\Program Files\HiveMQ\HiveMQ\windows-service\wrapper.jar" -Xrs -Dwrapper.service=true "-Dwrapper.working.dir=C:\Program Files\HiveMQ\HiveMQ\bin" "-Djna_tmpdir=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/../tmp" "-Dwrapper_home=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/.." "-Dwrapper.config=C:\Program Files\HiveMQ\HiveMQ\windows-service\conf\wrapper.conf" -Dwrapper.additional.1x=-Xrs "-Djna_tmpdir=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\..\tmp" org.rzo.yajsw.boot.WrapperServiceBooter 

C:\Windows\system32>java.exe -classpath "C:\Program Files\HiveMQ\HiveMQ\windows-service\wrapper.jar" -Xrs -Dwrapper.service=true "-Dwrapper.working.dir=C:\Program Files\HiveMQ\HiveMQ\bin" "-Djna_tmpdir=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/../tmp" "-Dwrapper_home=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\/.." "-Dwrapper.config=C:\Program Files\HiveMQ\HiveMQ\windows-service\conf\wrapper.conf" -Dwrapper.additional.1x=-Xrs "-Djna_tmpdir=C:\Program Files\HiveMQ\HiveMQ\windows-service\bat\..\tmp" org.rzo.yajsw.boot.WrapperServiceBooter
Feb 12, 2024 4:40:25 PM org.apache.commons.vfs2.VfsLog info
INFO: Using "C:\Users\ADMUSR~1\AppData\Local\Temp\vfs_cache" as temporary files store.
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:118)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.rzo.yajsw.boot.WrapperServiceBooter.main(WrapperServiceBooter.java:46)
Caused by: java.lang.IllegalAccessError: class org.rzo.yajsw.wrapper.AbstractWrappedProcess (in unnamed module @0x6a024a67) cannot access class sun.security.action.GetPropertyAction (in module java.base) because module java.base does not export sun.security.action to unnamed module @0x6a024a67
        at org.rzo.yajsw.wrapper.AbstractWrappedProcess.<clinit>(AbstractWrappedProcess.java:242)
        at org.rzo.yajsw.wrapper.WrappedProcessFactory.createProcess(WrappedProcessFactory.java:38)
        at org.rzo.yajsw.app.WrapperMainServiceWin.main(WrapperMainServiceWin.java:144)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        ... 2 more`

## To Reproduce
Follow instructions on HiveMQ Manual to install as Windows Service.

### Steps
Copy ZIP file content in HiveMQ home folder and execute the BAT file to register as a windows service as Administrator

- Affected HiveMQ CE version(s): 2024.02
- Used JVM version: jdk-21.0.1/64

**Comment by Terr4** [comment]
Any suggestion how to fix this?
I get the same error with HiveMQ CE version 2024.7 and 2024.8 using "OpenJDK 21.0.4 2024-07-16 LTS" on Windows Server 2022
